version: "3.9"

services:
    php:
        container_name: php-fpm
        build: ./docker/php
        ports:
            - 9000:9000
        volumes: 
            - ./app:/var/www
        restart: always
    
    apache:
        image: nginx
        container_name: http-server
        depends_on: 
            - php
        volumes: 
            - "./app:/var/www"   
            - "./docker/nginx/app-vhost.conf:/etc/nginx/conf.d/default.conf"
        ports: 
            - "8080:80"
        links: 
            - php
        restart: always